services:
  - type: web
    name: wiki-farm
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
    disk:
      - name: db
        mountPath: /opt/render/project/src/db
        sizeGB: 1
